### ISSUE TITLE
 validation.model.validator 无法使用keypath获取model

### ISSUE THREAD

**Issue by xdliuyong** [vuejs/vue-validator#12]
您好！非常感谢您提供的validator，在以下应用场景出了点问题。
```html
  <input type="text" class="form-control"  v-model="company.org_name" v-validate="required">
  <div>
    <span v-if="validation.company.org_name.required">required your company org_name.</span>
  </div>
```
validation.company.org_name.required 无法正确的获取到model， 在线急等。

**Comment by yyx990803** [comment]
I'm not the maintainer of this plugin - @kazupon is. He doesn't speak Chinese so please use English.

**Comment by kazupon** [comment]
@yyx990803 
Thank you for your follow. :)

**Comment by kazupon** [comment]
@xdliuyong 
Thank you for reporting.

In [jsfiddle](https://jsfiddle.net/kazupon/9817sptj/6/), I tried your the above code.

I understood the issue.
I will fix from now.

**Comment by kazupon** [comment]
I fixed this issue.
Please try to use vue-validator latest version. :)

**Comment by xdliuyong** [comment]
ok  thank you.
