### ISSUE TITLE
'min' and 'max' rules fail when using the official 'cast to number' feature

### ISSUE THREAD

**Issue by Stolz** [vuejs/vue-validator#13]
According to the [Vue.js docs](http://vuejs.org/guide/forms.html#Casting_Value_as_Number) user input can  be automatically persisted as numbers by adding the `number` attribute

    <input v-model="age" number>

In this scenario, both 'min' and 'max' validation rules fail as they are [coded](https://github.com/vuejs/vue-validator/blob/master/lib/validates.js#L81) to expect a string representing a number and not an actual number.

I think they should be compatible with the 'cast to number' feature.

**Comment by kazupon** [comment]
Thank you for reporting.

You're right...
I will fix from now.

**Comment by kazupon** [comment]
I fixed this issue.

https://github.com/vuejs/vue-validator/blob/master/HISTORY.md#v104--2015-05-08

Please try to use vue-validator latest version. :)

**Comment by Stolz** [comment]
Thanks @kazupon.

It's working now.
