### ISSUE TITLE
validator doesn't resolve dynamic models

### ISSUE THREAD

**Issue by pkat** [vuejs/vue-validator#14]
I have inputs that are dynamically created, so i may have a model that is set to `v-model="entityModel[key]"`. The `key` could be from a iterating array. Vue validator doesn't resolve the key, so if the key were `test`, instead of `entityModel.test` i end up with `entityModel[key]`. Any way around this?

**Comment by kazupon** [comment]
Can you please provide example code in jsfiddle ?

**Comment by silasrm** [comment]
I need validate a items on one dynamic list (http://jsfiddle.net/0bsn9pdL/1/), but I don't get success on this validation.

Tests failed:

`<span class="help-inline" v-if="validation.itens.$index.farmaco_id.required">My error message</span>`

or

`<span class="help-inline" v-if="validation.itens[$index].farmaco_id.required">My error message</span>`

**Comment by kazupon** [comment]
Sorry for the late relpy.

I think that this issue can resolve you use `v-component` directive.

like this:

https://jsfiddle.net/kazupon/xkkcrzn7/5/

**Comment by silasrm** [comment]
No problem dude.
`v-component` is amazing! This solve my problem.

Final version of my test: https://jsfiddle.net/cwjtta99/7/

**Comment by silasrm** [comment]
~~One question:~~

~~Why the default value of `quantidade` property of the data v-component element, is not setted on input with model `quantidade`?~~

Sorry! I set `value=""` on elements and not "see" this wrong before. :(

Test fixed https://jsfiddle.net/cwjtta99/8/
