### ISSUE TITLE
input绑定v-model后触发了死循环

### ISSUE THREAD

**Issue by jackzhaojun** [vuejs/vue-validator#337]
### vue & vue-validator version
2.0.3, 3.0.0-alpha.1

按照你的示例[https://github.com/vuejs/vue-validator/blob/dev/examples/started/index.html]( https://github.com/vuejs/vue-validator/blob/dev/examples/started/index.html)
我在input上绑定了v-model之后触发了死循环。

我在示例中添加的代码

```javascript
data: {
       inputValue: '',
       result: {},
       events: []
 }
```

```html
<input type="text" @input="handleValidate" v-model="inputValue" >
```
当你在input中输入第二个字符的时候就会引发死循环。

@input 替换为 @change后是可以正确运行的。

**Comment by kazupon** [comment]
sorry, this is alpha version yet.
I'll try to fix the v-model integration.
