### ISSUE TITLE
Feature request: touched indicator (like AngularJS $touched)

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vue-validator#5]
It would be nice to have a validation.model.touched that is set when a control blurs after receiving focus. If a field starts off invalid, then dirty isn't sufficient to cause error display if they visit the input but don't change the value.

BTW, nice plugin!

**Comment by davidkhess** [comment]
It would also be nice to have a way you can mark all fields as touched. So, when the VM takes a submit action of some sort, it can call that to ensure that all invalid conditions are properly displayed regardless of whether the field was visited or dirty.

**Comment by karol-f** [comment]
+1 for $touched

**Comment by kazupon** [comment]
Implemented in 2.0.0-alpha.1
https://github.com/vuejs/vue-validator#validation-result-structure
