### ISSUE TITLE
Feature request: make v-validate reactive

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vue-validator#6]
It appears that v-validate is a literal directive. It would be nice if it were reactive so that you could enable or disable validations under certain conditions. For instance, for a field that is sometimes required.

EDIT

I suppose a workaround (or perhaps what is the intended solution) would be to use a custom validator in this case.

**Comment by fivetwelve** [comment]
I agree. It would be nice to pass in an expression to the directive so the validate parameter may be dynamic. It would go a long way to allowing an input field to be more generic and re-usable.

**Comment by kazupon** [comment]
I'm going to support at next version.

**Comment by erguotou520** [comment]
Is this resolved? Here is a test
https://jsfiddle.net/jLcjzf08/
The `rules.required.rule` is dynamic, but the error message always show when empty input.

### VueValidator version

2.1.4

### Vue version

1.0.26

**Comment by kazupon** [comment]
related #217
see more:
https://github.com/vuejs/vue-validator/issues/217#issuecomment-218099304

However, I found the other bug that cannot change the validation message. 😇 
https://jsfiddle.net/kazupon/04nso4nm/1/

I'll fix try to it.

**Comment by erguotou520** [comment]
It means that I should define a custom validator to make it reactive?

**Comment by kazupon** [comment]
@erguotou520 
No.

I checked your reporting issue again.
validation rule and message did not become reactive.
This is bug.

I registered this issue.
https://github.com/vuejs/vue-validator/issues/284

**Comment by kazupon** [comment]
Fixed
https://github.com/vuejs/vue-validator/releases/tag/v2.1.5

**Comment by erguotou520** [comment]
I means that I have to custom a validator to realize `dynamic required`?
